#Application Configuration
server:
  port: 8093

# To See H2 Console in Browser:
# http://localhost:8093/h2-console
# Enabling H2 Console
spring:

  # ===============================
  # DB
  # ===============================
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    url: jdbc:postgresql://localhost:5432/Shopping-Microservices
    username: postgres
  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/
Feign:
  hystrix:
    enable: true
  circuitbreaker:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
